using GenclikMerkezi.Modules.Website.Features.ActivateContentCategory;
using GenclikMerkezi.Modules.Website.Features.ActivateContentType;
using GenclikMerkezi.Modules.Website.Features.ActivateFormDefinition;
using GenclikMerkezi.Modules.Website.Features.ActivateImpactMetric;
using GenclikMerkezi.Modules.Website.Features.ActivatePartner;
using GenclikMerkezi.Modules.Website.Features.ActivatePopup;
using GenclikMerkezi.Modules.Website.Features.ActivateSiteLanguage;
using GenclikMerkezi.Modules.Website.Features.ActivateVideo;
using GenclikMerkezi.Modules.Website.Features.AddFormSubmissionNote;
using GenclikMerkezi.Modules.Website.Features.ArchiveContentItem;
using GenclikMerkezi.Modules.Website.Features.ArchiveFormSubmission;
using GenclikMerkezi.Modules.Website.Features.AssignFormSubmission;
using GenclikMerkezi.Modules.Website.Features.ChangeFormSubmissionStatus;
using GenclikMerkezi.Modules.Website.Features.ConvertNotFoundPathToRedirect;
using GenclikMerkezi.Modules.Website.Features.CreateContentCategory;
using GenclikMerkezi.Modules.Website.Features.CreateContentItem;
using GenclikMerkezi.Modules.Website.Features.CreateContentPreviewLink;
using GenclikMerkezi.Modules.Website.Features.CreateContentType;
using GenclikMerkezi.Modules.Website.Features.CreateRedirect;
using GenclikMerkezi.Modules.Website.Features.CreateSiteLanguage;
using GenclikMerkezi.Modules.Website.Features.CreateFormDefinition;
using GenclikMerkezi.Modules.Website.Features.CreateImpactMetric;
using GenclikMerkezi.Modules.Website.Features.CreateLegalDocument;
using GenclikMerkezi.Modules.Website.Features.CreateLegalDocumentDraft;
using GenclikMerkezi.Modules.Website.Features.CreatePartner;
using GenclikMerkezi.Modules.Website.Features.CreatePopup;
using GenclikMerkezi.Modules.Website.Features.CreateSlider;
using GenclikMerkezi.Modules.Website.Features.CreateVideo;
using GenclikMerkezi.Modules.Website.Features.DeactivateContentCategory;
using GenclikMerkezi.Modules.Website.Features.DeactivateContentType;
using GenclikMerkezi.Modules.Website.Features.DeactivateImpactMetric;
using GenclikMerkezi.Modules.Website.Features.DeactivatePartner;
using GenclikMerkezi.Modules.Website.Features.DeactivatePopup;
using GenclikMerkezi.Modules.Website.Features.DeactivateSiteLanguage;
using GenclikMerkezi.Modules.Website.Features.DeactivateFormDefinition;
using GenclikMerkezi.Modules.Website.Features.DeactivateVideo;
using GenclikMerkezi.Modules.Website.Features.DeleteContentCategory;
using GenclikMerkezi.Modules.Website.Features.DeleteContentCategoryTranslation;
using GenclikMerkezi.Modules.Website.Features.DeleteContentItem;
using GenclikMerkezi.Modules.Website.Features.DeleteContentItemTranslation;
using GenclikMerkezi.Modules.Website.Features.DeleteContentTypeTranslation;
using GenclikMerkezi.Modules.Website.Features.DeleteFormDefinition;
using GenclikMerkezi.Modules.Website.Features.DeleteFormDefinitionTranslation;
using GenclikMerkezi.Modules.Website.Features.DeleteImpactMetric;
using GenclikMerkezi.Modules.Website.Features.DeleteImpactMetricTranslation;
using GenclikMerkezi.Modules.Website.Features.DeleteLegalDocument;
using GenclikMerkezi.Modules.Website.Features.DeleteLegalDocumentDraft;
using GenclikMerkezi.Modules.Website.Features.DeleteMediaAsset;
using GenclikMerkezi.Modules.Website.Features.DeleteNotFoundPath;
using GenclikMerkezi.Modules.Website.Features.DeletePartner;
using GenclikMerkezi.Modules.Website.Features.DeletePartnerTranslation;
using GenclikMerkezi.Modules.Website.Features.DeletePopup;
using GenclikMerkezi.Modules.Website.Features.DeletePopupTranslation;
using GenclikMerkezi.Modules.Website.Features.DeleteRedirect;
using GenclikMerkezi.Modules.Website.Features.DeleteSlider;
using GenclikMerkezi.Modules.Website.Features.DeleteTag;
using GenclikMerkezi.Modules.Website.Features.DeleteVideo;
using GenclikMerkezi.Modules.Website.Features.DeleteVideoTranslation;
using GenclikMerkezi.Modules.Website.Features.DiscardContentLayoutDraft;
using GenclikMerkezi.Modules.Website.Features.DiscardHomeLayoutDraft;
using GenclikMerkezi.Modules.Website.Features.DownloadFormSubmissionFile;
using GenclikMerkezi.Modules.Website.Features.DuplicateContentItem;
using GenclikMerkezi.Modules.Website.Features.GetBlockTypes;
using GenclikMerkezi.Modules.Website.Features.GetContentCategoriesByType;
using GenclikMerkezi.Modules.Website.Features.GetFormDefinitionById;
using GenclikMerkezi.Modules.Website.Features.GetFormDefinitions;
using GenclikMerkezi.Modules.Website.Features.GetFormSubmissionById;
using GenclikMerkezi.Modules.Website.Features.GetFormSubmissions;
using GenclikMerkezi.Modules.Website.Features.GetContentItemById;
using GenclikMerkezi.Modules.Website.Features.GetContentItems;
using GenclikMerkezi.Modules.Website.Features.GetContentLayout;
using GenclikMerkezi.Modules.Website.Features.GetContentPreview;
using GenclikMerkezi.Modules.Website.Features.GetContentTrash;
using GenclikMerkezi.Modules.Website.Features.GetPersonalDataAccessLog;
using GenclikMerkezi.Modules.Website.Features.GetPublicContentById;
using GenclikMerkezi.Modules.Website.Features.GetPublicContents;
using GenclikMerkezi.Modules.Website.Features.GetPublicForm;
using GenclikMerkezi.Modules.Website.Features.GetPublicHome;
using GenclikMerkezi.Modules.Website.Features.GetPublicLegalDocument;
using GenclikMerkezi.Modules.Website.Features.GetPublicLegalDocumentVersion;
using GenclikMerkezi.Modules.Website.Features.GetContentTypeById;
using GenclikMerkezi.Modules.Website.Features.GetContentTypes;
using GenclikMerkezi.Modules.Website.Features.GetHomeLayout;
using GenclikMerkezi.Modules.Website.Features.GetHomeLayoutPreview;
using GenclikMerkezi.Modules.Website.Features.GetImpactMetricById;
using GenclikMerkezi.Modules.Website.Features.GetImpactMetrics;
using GenclikMerkezi.Modules.Website.Features.GetLegalDocumentById;
using GenclikMerkezi.Modules.Website.Features.GetLegalDocuments;
using GenclikMerkezi.Modules.Website.Features.GetMediaAssetById;
using GenclikMerkezi.Modules.Website.Features.GetMediaAssetFolders;
using GenclikMerkezi.Modules.Website.Features.GetMediaAssets;
using GenclikMerkezi.Modules.Website.Features.GetMenuByLocation;
using GenclikMerkezi.Modules.Website.Features.GetMenus;
using GenclikMerkezi.Modules.Website.Features.GetNotFoundPaths;
using GenclikMerkezi.Modules.Website.Features.GetPartnerById;
using GenclikMerkezi.Modules.Website.Features.GetPartners;
using GenclikMerkezi.Modules.Website.Features.GetPopupById;
using GenclikMerkezi.Modules.Website.Features.GetPopups;
using GenclikMerkezi.Modules.Website.Features.GetPublicPartners;
using GenclikMerkezi.Modules.Website.Features.GetPublicSite;
using GenclikMerkezi.Modules.Website.Features.GetPublicVideos;
using GenclikMerkezi.Modules.Website.Features.GetRedirects;
using GenclikMerkezi.Modules.Website.Features.GetSiteLanguages;
using GenclikMerkezi.Modules.Website.Features.GetSiteSettings;
using GenclikMerkezi.Modules.Website.Features.GetSliderById;
using GenclikMerkezi.Modules.Website.Features.GetSliders;
using GenclikMerkezi.Modules.Website.Features.GetSubmissionToken;
using GenclikMerkezi.Modules.Website.Features.GetTags;
using GenclikMerkezi.Modules.Website.Features.GetVideoById;
using GenclikMerkezi.Modules.Website.Features.GetVideos;
using GenclikMerkezi.Modules.Website.Features.MergeTag;
using GenclikMerkezi.Modules.Website.Features.PermanentlyDeleteContentItem;
using GenclikMerkezi.Modules.Website.Features.PublishContentItem;
using GenclikMerkezi.Modules.Website.Features.PublishLegalDocumentDraft;
using GenclikMerkezi.Modules.Website.Features.PublishContentLayout;
using GenclikMerkezi.Modules.Website.Features.PublishHomeLayout;
using GenclikMerkezi.Modules.Website.Features.ReplaceContentDraftBlocks;
using GenclikMerkezi.Modules.Website.Features.ReplaceHomeDraftBlocks;
using GenclikMerkezi.Modules.Website.Features.ReplaceMenuItems;
using GenclikMerkezi.Modules.Website.Features.ReplaceSlides;
using GenclikMerkezi.Modules.Website.Features.ResolveRoute;
using GenclikMerkezi.Modules.Website.Features.RestoreContentItem;
using GenclikMerkezi.Modules.Website.Features.ScheduleContentItem;
using GenclikMerkezi.Modules.Website.Features.SetContentItemAttachments;
using GenclikMerkezi.Modules.Website.Features.SetContentItemCategories;
using GenclikMerkezi.Modules.Website.Features.SetContentItemForm;
using GenclikMerkezi.Modules.Website.Features.SetContentItemGallery;
using GenclikMerkezi.Modules.Website.Features.SetContentItemParent;
using GenclikMerkezi.Modules.Website.Features.SetContentItemRelatedContent;
using GenclikMerkezi.Modules.Website.Features.SetContentItemTranslationTags;
using GenclikMerkezi.Modules.Website.Features.SetContentItemVideos;
using GenclikMerkezi.Modules.Website.Features.SetDefaultSiteLanguage;
using GenclikMerkezi.Modules.Website.Features.SetFormFields;
using GenclikMerkezi.Modules.Website.Features.SubmitFormSubmission;
using GenclikMerkezi.Modules.Website.Features.UnarchiveContentItem;
using GenclikMerkezi.Modules.Website.Features.UnarchiveFormSubmission;
using GenclikMerkezi.Modules.Website.Features.UnpublishContentItem;
using GenclikMerkezi.Modules.Website.Features.UpdateContentCategory;
using GenclikMerkezi.Modules.Website.Features.UpdateContentCategoryTranslation;
using GenclikMerkezi.Modules.Website.Features.UpdateContentItem;
using GenclikMerkezi.Modules.Website.Features.UpdateContentItemTranslation;
using GenclikMerkezi.Modules.Website.Features.UpdateContentType;
using GenclikMerkezi.Modules.Website.Features.UpdateContentTypeTranslation;
using GenclikMerkezi.Modules.Website.Features.UpdateFormDefinition;
using GenclikMerkezi.Modules.Website.Features.UpdateFormDefinitionTranslation;
using GenclikMerkezi.Modules.Website.Features.UpdateImpactMetric;
using GenclikMerkezi.Modules.Website.Features.UpdateImpactMetricTranslation;
using GenclikMerkezi.Modules.Website.Features.UpdateLegalDocumentDraftBody;
using GenclikMerkezi.Modules.Website.Features.UpdateLegalDocumentTranslation;
using GenclikMerkezi.Modules.Website.Features.UpdateMediaAsset;
using GenclikMerkezi.Modules.Website.Features.UpdatePartner;
using GenclikMerkezi.Modules.Website.Features.UpdatePartnerTranslation;
using GenclikMerkezi.Modules.Website.Features.UpdatePopup;
using GenclikMerkezi.Modules.Website.Features.UpdatePopupTranslation;
using GenclikMerkezi.Modules.Website.Features.UpdateRedirect;
using GenclikMerkezi.Modules.Website.Features.UpdateSiteLanguage;
using GenclikMerkezi.Modules.Website.Features.UpdateSlider;
using GenclikMerkezi.Modules.Website.Features.UpdateVideo;
using GenclikMerkezi.Modules.Website.Features.UpdateVideoTranslation;
using GenclikMerkezi.Modules.Website.Features.UpdateSiteSettingsBankAccounts;
using GenclikMerkezi.Modules.Website.Features.UpdateSiteSettingsBotProtection;
using GenclikMerkezi.Modules.Website.Features.UpdateSiteSettingsContact;
using GenclikMerkezi.Modules.Website.Features.UpdateSiteSettingsFeatures;
using GenclikMerkezi.Modules.Website.Features.UpdateSiteSettingsIdentity;
using GenclikMerkezi.Modules.Website.Features.UpdateSiteSettingsMaintenance;
using GenclikMerkezi.Modules.Website.Features.UpdateSiteSettingsSubmissions;
using GenclikMerkezi.Modules.Website.Features.UpdateSiteSettingsTheme;
using GenclikMerkezi.Modules.Website.Features.UpdateTag;
using GenclikMerkezi.Modules.Website.Features.UploadMediaAsset;
using Microsoft.AspNetCore.Routing;

namespace GenclikMerkezi.Modules.Website;

public static class WebsiteModuleEndpointExtensions
{
    public static IEndpointRouteBuilder MapWebsiteModuleEndpoints(this IEndpointRouteBuilder app)
    {
        CreateSiteLanguageEndpoint.Map(app);
        UpdateSiteLanguageEndpoint.Map(app);
        ActivateSiteLanguageEndpoint.Map(app);
        DeactivateSiteLanguageEndpoint.Map(app);
        SetDefaultSiteLanguageEndpoint.Map(app);
        GetSiteLanguagesEndpoint.Map(app);

        UploadMediaAssetEndpoint.Map(app);
        GetMediaAssetsEndpoint.Map(app);
        GetMediaAssetFoldersEndpoint.Map(app);
        GetMediaAssetByIdEndpoint.Map(app);
        UpdateMediaAssetEndpoint.Map(app);
        DeleteMediaAssetEndpoint.Map(app);

        GetSiteSettingsEndpoint.Map(app);
        UpdateSiteSettingsIdentityEndpoint.Map(app);
        UpdateSiteSettingsThemeEndpoint.Map(app);
        UpdateSiteSettingsContactEndpoint.Map(app);
        UpdateSiteSettingsBankAccountsEndpoint.Map(app);
        UpdateSiteSettingsFeaturesEndpoint.Map(app);
        UpdateSiteSettingsMaintenanceEndpoint.Map(app);
        UpdateSiteSettingsBotProtectionEndpoint.Map(app);
        UpdateSiteSettingsSubmissionsEndpoint.Map(app);
        GetPublicSiteEndpoint.Map(app);

        CreateContentTypeEndpoint.Map(app);
        UpdateContentTypeEndpoint.Map(app);
        UpdateContentTypeTranslationEndpoint.Map(app);
        DeleteContentTypeTranslationEndpoint.Map(app);
        ActivateContentTypeEndpoint.Map(app);
        DeactivateContentTypeEndpoint.Map(app);
        GetContentTypesEndpoint.Map(app);
        GetContentTypeByIdEndpoint.Map(app);

        CreateContentItemEndpoint.Map(app);
        UpdateContentItemEndpoint.Map(app);
        UpdateContentItemTranslationEndpoint.Map(app);
        DeleteContentItemTranslationEndpoint.Map(app);
        PublishContentItemEndpoint.Map(app);
        UnpublishContentItemEndpoint.Map(app);
        ArchiveContentItemEndpoint.Map(app);
        UnarchiveContentItemEndpoint.Map(app);
        ScheduleContentItemEndpoint.Map(app);
        SetContentItemParentEndpoint.Map(app);
        GetContentItemsEndpoint.Map(app);
        GetContentItemByIdEndpoint.Map(app);
        DeleteContentItemEndpoint.Map(app);
        GetContentTrashEndpoint.Map(app);
        RestoreContentItemEndpoint.Map(app);
        PermanentlyDeleteContentItemEndpoint.Map(app);
        DuplicateContentItemEndpoint.Map(app);
        CreateContentPreviewLinkEndpoint.Map(app);
        GetContentPreviewEndpoint.Map(app);
        GetPublicContentsEndpoint.Map(app);
        GetPublicContentByIdEndpoint.Map(app);

        CreateRedirectEndpoint.Map(app);
        UpdateRedirectEndpoint.Map(app);
        DeleteRedirectEndpoint.Map(app);
        GetRedirectsEndpoint.Map(app);

        GetNotFoundPathsEndpoint.Map(app);
        DeleteNotFoundPathEndpoint.Map(app);
        ConvertNotFoundPathToRedirectEndpoint.Map(app);

        ResolveRouteEndpoint.Map(app);

        CreateVideoEndpoint.Map(app);
        UpdateVideoEndpoint.Map(app);
        UpdateVideoTranslationEndpoint.Map(app);
        DeleteVideoTranslationEndpoint.Map(app);
        ActivateVideoEndpoint.Map(app);
        DeactivateVideoEndpoint.Map(app);
        DeleteVideoEndpoint.Map(app);
        GetVideosEndpoint.Map(app);
        GetVideoByIdEndpoint.Map(app);
        GetPublicVideosEndpoint.Map(app);

        CreateContentCategoryEndpoint.Map(app);
        UpdateContentCategoryEndpoint.Map(app);
        UpdateContentCategoryTranslationEndpoint.Map(app);
        DeleteContentCategoryTranslationEndpoint.Map(app);
        ActivateContentCategoryEndpoint.Map(app);
        DeactivateContentCategoryEndpoint.Map(app);
        DeleteContentCategoryEndpoint.Map(app);
        GetContentCategoriesByTypeEndpoint.Map(app);

        GetTagsEndpoint.Map(app);
        UpdateTagEndpoint.Map(app);
        DeleteTagEndpoint.Map(app);
        MergeTagEndpoint.Map(app);

        SetContentItemCategoriesEndpoint.Map(app);
        SetContentItemTranslationTagsEndpoint.Map(app);
        SetContentItemGalleryEndpoint.Map(app);
        SetContentItemVideosEndpoint.Map(app);
        SetContentItemAttachmentsEndpoint.Map(app);
        SetContentItemRelatedContentEndpoint.Map(app);
        SetContentItemFormEndpoint.Map(app);

        GetMenusEndpoint.Map(app);
        GetMenuByLocationEndpoint.Map(app);
        ReplaceMenuItemsEndpoint.Map(app);

        CreateSliderEndpoint.Map(app);
        GetSlidersEndpoint.Map(app);
        GetSliderByIdEndpoint.Map(app);
        UpdateSliderEndpoint.Map(app);
        ReplaceSlidesEndpoint.Map(app);
        DeleteSliderEndpoint.Map(app);

        CreatePartnerEndpoint.Map(app);
        UpdatePartnerEndpoint.Map(app);
        UpdatePartnerTranslationEndpoint.Map(app);
        DeletePartnerTranslationEndpoint.Map(app);
        ActivatePartnerEndpoint.Map(app);
        DeactivatePartnerEndpoint.Map(app);
        DeletePartnerEndpoint.Map(app);
        GetPartnersEndpoint.Map(app);
        GetPartnerByIdEndpoint.Map(app);
        GetPublicPartnersEndpoint.Map(app);

        CreateImpactMetricEndpoint.Map(app);
        UpdateImpactMetricEndpoint.Map(app);
        UpdateImpactMetricTranslationEndpoint.Map(app);
        DeleteImpactMetricTranslationEndpoint.Map(app);
        ActivateImpactMetricEndpoint.Map(app);
        DeactivateImpactMetricEndpoint.Map(app);
        DeleteImpactMetricEndpoint.Map(app);
        GetImpactMetricsEndpoint.Map(app);
        GetImpactMetricByIdEndpoint.Map(app);

        CreatePopupEndpoint.Map(app);
        UpdatePopupEndpoint.Map(app);
        UpdatePopupTranslationEndpoint.Map(app);
        DeletePopupTranslationEndpoint.Map(app);
        ActivatePopupEndpoint.Map(app);
        DeactivatePopupEndpoint.Map(app);
        DeletePopupEndpoint.Map(app);
        GetPopupsEndpoint.Map(app);
        GetPopupByIdEndpoint.Map(app);

        GetBlockTypesEndpoint.Map(app);
        GetHomeLayoutEndpoint.Map(app);
        GetContentLayoutEndpoint.Map(app);
        ReplaceHomeDraftBlocksEndpoint.Map(app);
        ReplaceContentDraftBlocksEndpoint.Map(app);
        PublishHomeLayoutEndpoint.Map(app);
        PublishContentLayoutEndpoint.Map(app);
        DiscardHomeLayoutDraftEndpoint.Map(app);
        DiscardContentLayoutDraftEndpoint.Map(app);
        GetHomeLayoutPreviewEndpoint.Map(app);
        GetPublicHomeEndpoint.Map(app);

        // ADR-024 §12.3 (Faz 3 Görev 1): anonymous submission protection - the form/newsletter/cookie
        // consent endpoints added in later Görev's all depend on this token.
        GetSubmissionTokenEndpoint.Map(app);

        // ADR-024 §12.1 (Faz 3 Görev 2): versioned legal documents, entirely panel-managed.
        CreateLegalDocumentEndpoint.Map(app);
        UpdateLegalDocumentTranslationEndpoint.Map(app);
        CreateLegalDocumentDraftEndpoint.Map(app);
        UpdateLegalDocumentDraftBodyEndpoint.Map(app);
        PublishLegalDocumentDraftEndpoint.Map(app);
        DeleteLegalDocumentDraftEndpoint.Map(app);
        DeleteLegalDocumentEndpoint.Map(app);
        GetLegalDocumentsEndpoint.Map(app);
        GetLegalDocumentByIdEndpoint.Map(app);
        GetPublicLegalDocumentEndpoint.Map(app);
        GetPublicLegalDocumentVersionEndpoint.Map(app);

        // ADR-024 §12.2 (Faz 3 Görev 3): form definitions and content-form linking.
        CreateFormDefinitionEndpoint.Map(app);
        UpdateFormDefinitionEndpoint.Map(app);
        UpdateFormDefinitionTranslationEndpoint.Map(app);
        DeleteFormDefinitionTranslationEndpoint.Map(app);
        SetFormFieldsEndpoint.Map(app);
        ActivateFormDefinitionEndpoint.Map(app);
        DeactivateFormDefinitionEndpoint.Map(app);
        DeleteFormDefinitionEndpoint.Map(app);
        GetFormDefinitionsEndpoint.Map(app);
        GetFormDefinitionByIdEndpoint.Map(app);
        GetPublicFormEndpoint.Map(app);
        SubmitFormSubmissionEndpoint.Map(app);

        // ADR-024 §12.2 (Faz 3 Görev 5): submission management, archive/anonymization and the personal
        // data access log.
        GetFormSubmissionsEndpoint.Map(app);
        GetFormSubmissionByIdEndpoint.Map(app);
        DownloadFormSubmissionFileEndpoint.Map(app);
        ChangeFormSubmissionStatusEndpoint.Map(app);
        AssignFormSubmissionEndpoint.Map(app);
        AddFormSubmissionNoteEndpoint.Map(app);
        ArchiveFormSubmissionEndpoint.Map(app);
        UnarchiveFormSubmissionEndpoint.Map(app);
        GetPersonalDataAccessLogEndpoint.Map(app);

        return app;
    }
}
