// <auto-generated />
using System;
using GenclikMerkezi.Modules.Candidate.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenclikMerkezi.Modules.Candidate.Infrastructure.Migrations
{
    [DbContext(typeof(CandidateDbContext))]
    [Migration("20260918073529_AddCandidateSearchIndex")]
    partial class AddCandidateSearchIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateCv", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("CareerAdvisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("int");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DistrictId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DriversLicenseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("GenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("MilitaryStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NationalityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("NetSalaryExpectation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CandidateCvs", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateCvContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateCvId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComputerSkills")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Hobbies")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCvId")
                        .IsUnique();

                    b.ToTable("CandidateCvContents", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateCvContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsNativeLanguage")
                        .HasColumnType("bit");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCvContentId");

                    b.ToTable("CandidateLanguages", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateCvContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ReferenceLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferenceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCvContentId");

                    b.ToTable("CandidateReferences", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateSearchIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("int");

                    b.Property<Guid?>("DistrictId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullNameNormalized")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid?>("ProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompletionPercentage");

                    b.HasIndex("DistrictId");

                    b.HasIndex("FullNameNormalized");

                    b.HasIndex("ProvinceId");

                    b.ToTable("CandidateSearchIndex", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateSearchIndexEducationLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateSearchIndexId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EducationLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("CandidateSearchIndexId", "EducationLevelId")
                        .IsUnique();

                    b.ToTable("CandidateSearchIndexEducationLevels", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateSearchIndexSector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateSearchIndexId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("CandidateSearchIndexId", "SectorId")
                        .IsUnique();

                    b.ToTable("CandidateSearchIndexSectors", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateCvContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("CertificateDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IssuingInstitution")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCvContentId");

                    b.ToTable("Certificates", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateCvContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("DiplomaGrade")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid?>("DiplomaGradingSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EducationLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchoolNameFreeText")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCvContentId");

                    b.ToTable("Educations", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateCvContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmploymentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrentJob")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("WorkFieldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCvContentId");

                    b.ToTable("Experiences", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.SocialMediaLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateCvId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCvId");

                    b.ToTable("SocialMediaLinks", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateCv", b =>
                {
                    b.OwnsOne("GenclikMerkezi.SharedKernel.Domain.FileAttachment", "Photo", b1 =>
                        {
                            b1.Property<Guid>("CandidateCvId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PhotoContentType");

                            b1.Property<string>("FileKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("PhotoFileKey");

                            b1.Property<string>("OriginalFileName")
                                .IsRequired()
                                .HasMaxLength(260)
                                .HasColumnType("nvarchar(260)")
                                .HasColumnName("PhotoOriginalFileName");

                            b1.Property<Guid>("OwnerEntityId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("PhotoOwnerEntityId");

                            b1.Property<string>("OwnerEntityType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PhotoOwnerEntityType");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("PhotoSizeInBytes");

                            b1.Property<DateTime>("UploadedAtUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("PhotoUploadedAtUtc");

                            b1.HasKey("CandidateCvId");

                            b1.ToTable("CandidateCvs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CandidateCvId");
                        });

                    b.OwnsOne("GenclikMerkezi.Modules.Candidate.Domain.DisabilityInfo", "DisabilityInfo", b1 =>
                        {
                            b1.Property<Guid>("CandidateCvId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("DisabilityCategoryId");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("DisabilityDescription");

                            b1.Property<bool>("HasChronicCondition")
                                .HasColumnType("bit")
                                .HasColumnName("DisabilityHasChronicCondition");

                            b1.Property<bool>("HasConsciousnessLossRisk")
                                .HasColumnType("bit")
                                .HasColumnName("DisabilityHasConsciousnessLossRisk");

                            b1.Property<bool>("HasContagiousDisease")
                                .HasColumnType("bit")
                                .HasColumnName("DisabilityHasContagiousDisease");

                            b1.Property<bool>("HasHealthReport")
                                .HasColumnType("bit")
                                .HasColumnName("DisabilityHasHealthReport");

                            b1.Property<int>("Percentage")
                                .HasColumnType("int")
                                .HasColumnName("DisabilityPercentage");

                            b1.Property<bool>("UsesMedication")
                                .HasColumnType("bit")
                                .HasColumnName("DisabilityUsesMedication");

                            b1.HasKey("CandidateCvId");

                            b1.ToTable("CandidateCvs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CandidateCvId");
                        });

                    b.Navigation("DisabilityInfo");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateCvContent", b =>
                {
                    b.OwnsOne("GenclikMerkezi.SharedKernel.Domain.FileAttachment", "CvFile", b1 =>
                        {
                            b1.Property<Guid>("CandidateCvContentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CvFileContentType");

                            b1.Property<string>("FileKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("CvFileKey");

                            b1.Property<string>("OriginalFileName")
                                .IsRequired()
                                .HasMaxLength(260)
                                .HasColumnType("nvarchar(260)")
                                .HasColumnName("CvFileOriginalFileName");

                            b1.Property<Guid>("OwnerEntityId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("CvFileOwnerEntityId");

                            b1.Property<string>("OwnerEntityType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CvFileOwnerEntityType");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("CvFileSizeInBytes");

                            b1.Property<DateTime>("UploadedAtUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("CvFileUploadedAtUtc");

                            b1.HasKey("CandidateCvContentId");

                            b1.ToTable("CandidateCvContents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CandidateCvContentId");
                        });

                    b.Navigation("CvFile");
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateLanguage", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Candidate.Domain.CandidateCvContent", null)
                        .WithMany("Languages")
                        .HasForeignKey("CandidateCvContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateReference", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Candidate.Domain.CandidateCvContent", null)
                        .WithMany("References")
                        .HasForeignKey("CandidateCvContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateSearchIndexEducationLevel", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Candidate.Domain.CandidateSearchIndex", null)
                        .WithMany("EducationLevels")
                        .HasForeignKey("CandidateSearchIndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateSearchIndexSector", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Candidate.Domain.CandidateSearchIndex", null)
                        .WithMany("Sectors")
                        .HasForeignKey("CandidateSearchIndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.Certificate", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Candidate.Domain.CandidateCvContent", null)
                        .WithMany("Certificates")
                        .HasForeignKey("CandidateCvContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.Education", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Candidate.Domain.CandidateCvContent", null)
                        .WithMany("Educations")
                        .HasForeignKey("CandidateCvContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.Experience", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Candidate.Domain.CandidateCvContent", null)
                        .WithMany("Experiences")
                        .HasForeignKey("CandidateCvContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.SocialMediaLink", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Candidate.Domain.CandidateCv", null)
                        .WithMany("SocialMediaLinks")
                        .HasForeignKey("CandidateCvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateCv", b =>
                {
                    b.Navigation("SocialMediaLinks");
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateCvContent", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Languages");

                    b.Navigation("References");
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Candidate.Domain.CandidateSearchIndex", b =>
                {
                    b.Navigation("EducationLevels");

                    b.Navigation("Sectors");
                });
#pragma warning restore 612, 618
        }
    }
}
