// <auto-generated />
using System;
using GenclikMerkezi.Modules.CareerDevelopment.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenclikMerkezi.Modules.CareerDevelopment.Infrastructure.Migrations
{
    [DbContext(typeof(CareerDevelopmentDbContext))]
    partial class CareerDevelopmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenclikMerkezi.Modules.CareerDevelopment.Domain.AdvisorRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdvisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateCvId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCvId");

                    b.ToTable("AdvisorRecommendations", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.CareerDevelopment.Domain.CareerGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateCvId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("SetByAdvisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCvId");

                    b.ToTable("CareerGoals", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.CareerDevelopment.Domain.SkillGap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateCvId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IdentifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdentifiedByAdvisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCvId");

                    b.ToTable("SkillGaps", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.CareerDevelopment.Domain.TrainingRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateCvId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DevelopmentPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("RecommendedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecommendedByAdvisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCvId");

                    b.ToTable("TrainingRecommendations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
