using GenclikMerkezi.Modules.Employer.Domain;

namespace GenclikMerkezi.Modules.Employer.Features.GetCompany;

public sealed record GetCompanyResponse(
    Guid Id,
    Guid UserId,
    Guid? CareerAdvisorId,
    string Name,
    Guid SectorId,
    int? FoundedYear,
    int? EmployeeCount,
    string? WebsiteUrl,
    Guid CountryId,
    Guid ProvinceId,
    Guid DistrictId,
    string Address,
    string? AboutHtml,
    string ContactFirstName,
    string ContactLastName,
    string ContactEmail,
    string ContactPhone,
    Guid TaxOfficeId,
    string TaxNumber,
    bool MarketingConsent,
    CompanyStatus Status,
    Guid? ApprovedByUserId,
    DateTime? ApprovedAtUtc,
    string? RejectionReason,
    Guid? DeactivatedByUserId,
    DateTime? DeactivatedAtUtc,
    DateTime CreatedAtUtc)
{
    public static GetCompanyResponse FromDomain(Company company) => new(
        company.Id,
        company.UserId,
        company.CareerAdvisorId,
        company.Name,
        company.SectorId,
        company.FoundedYear,
        company.EmployeeCount,
        company.WebsiteUrl,
        company.CountryId,
        company.ProvinceId,
        company.DistrictId,
        company.Address,
        company.AboutHtml,
        company.ContactFirstName,
        company.ContactLastName,
        company.ContactEmail,
        company.ContactPhone,
        company.TaxOfficeId,
        company.TaxNumber,
        company.MarketingConsent,
        company.Status,
        company.ApprovedByUserId,
        company.ApprovedAtUtc,
        company.RejectionReason,
        company.DeactivatedByUserId,
        company.DeactivatedAtUtc,
        company.CreatedAtUtc);
}
