// <auto-generated />
using System;
using GenclikMerkezi.Modules.Website.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenclikMerkezi.Modules.Website.Infrastructure.Migrations
{
    [DbContext(typeof(WebsiteDbContext))]
    [Migration("20260923193341_AddMediaAsset")]
    partial class AddMediaAsset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenclikMerkezi.Modules.Website.Domain.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ContainsPersonalData")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Folder");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsagePermissionNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MediaAssets", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Website.Domain.SiteLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SiteLanguages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b20fca3c-d17b-8010-fcd8-bd94e7db0ca4"),
                            Code = "tr",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDefault = true,
                            Name = "Türkçe",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("a25a5495-704f-8605-9105-af910a4e37d5"),
                            Code = "en",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = false,
                            IsDefault = false,
                            Name = "English",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Website.Domain.MediaAsset", b =>
                {
                    b.OwnsOne("GenclikMerkezi.SharedKernel.Domain.FileAttachment", "Original", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OriginalContentType");

                            b1.Property<string>("FileKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("OriginalFileKey");

                            b1.Property<string>("OriginalFileName")
                                .IsRequired()
                                .HasMaxLength(260)
                                .HasColumnType("nvarchar(260)")
                                .HasColumnName("OriginalFileName");

                            b1.Property<Guid>("OwnerEntityId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OriginalOwnerEntityId");

                            b1.Property<string>("OwnerEntityType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OriginalOwnerEntityType");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("OriginalSizeInBytes");

                            b1.Property<DateTime>("UploadedAtUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("OriginalUploadedAtUtc");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("MediaAssets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsMany("GenclikMerkezi.Modules.Website.Domain.MediaAssetTranslation", "Translations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AltText")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Caption")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<string>("LanguageCode")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("nvarchar(35)")
                                .HasColumnName("LanguageCode");

                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("MediaAssetId", "LanguageCode")
                                .IsUnique();

                            b1.ToTable("MediaAssetTranslations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsMany("GenclikMerkezi.Modules.Website.Domain.MediaAssetVariant", "Variants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Height")
                                .HasColumnType("int");

                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("VariantName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<int>("Width")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("MediaAssetId");

                            b1.ToTable("MediaAssetVariants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("GenclikMerkezi.SharedKernel.Domain.FileAttachment", "File", b2 =>
                                {
                                    b2.Property<Guid>("MediaAssetVariantId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("ContentType");

                                    b2.Property<string>("FileKey")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)")
                                        .HasColumnName("FileKey");

                                    b2.Property<string>("OriginalFileName")
                                        .IsRequired()
                                        .HasMaxLength(260)
                                        .HasColumnType("nvarchar(260)")
                                        .HasColumnName("OriginalFileName");

                                    b2.Property<Guid>("OwnerEntityId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("OwnerEntityId");

                                    b2.Property<string>("OwnerEntityType")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("OwnerEntityType");

                                    b2.Property<long>("SizeInBytes")
                                        .HasColumnType("bigint")
                                        .HasColumnName("SizeInBytes");

                                    b2.Property<DateTime>("UploadedAtUtc")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("UploadedAtUtc");

                                    b2.HasKey("MediaAssetVariantId");

                                    b2.ToTable("MediaAssetVariants", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MediaAssetVariantId");
                                });

                            b1.Navigation("File")
                                .IsRequired();
                        });

                    b.Navigation("Original")
                        .IsRequired();

                    b.Navigation("Translations");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
