// <auto-generated />
using System;
using GenclikMerkezi.Modules.Employer.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenclikMerkezi.Modules.Employer.Infrastructure.Migrations
{
    [DbContext(typeof(EmployerDbContext))]
    [Migration("20260922144242_SuspendJob")]
    partial class SuspendJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutHtml")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CareerAdvisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeactivatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<bool>("MarketingConsent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("TaxOfficeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("TaxNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionHtml")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("EmploymentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExperienceLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsForDisabledCandidates")
                        .HasColumnType("bit");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByAdvisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevisionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SuspendedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SuspendedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("WorkLocationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.JobDrivingLicensePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriversLicenseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobDrivingLicensePreferences", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.JobEducationLevelPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EducationLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobEducationLevelPreferences", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.JobGenderPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobGenderPreferences", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.JobLanguageRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobLanguageRequirements", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.JobMilitaryStatusPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MilitaryStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobMilitaryStatusPreferences", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeed", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ClosedByAdvisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetailsText")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("EmploymentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExperienceLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FulfilledByCandidateCvId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PooledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PooledByAdvisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("WorkLocationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("PersonnelNeeds", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeedDrivingLicensePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriversLicenseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonnelNeedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelNeedId");

                    b.ToTable("PersonnelNeedDrivingLicensePreferences", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeedEducationLevelPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EducationLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonnelNeedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelNeedId");

                    b.ToTable("PersonnelNeedEducationLevelPreferences", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeedGenderPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonnelNeedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelNeedId");

                    b.ToTable("PersonnelNeedGenderPreferences", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeedMilitaryStatusPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MilitaryStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonnelNeedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelNeedId");

                    b.ToTable("PersonnelNeedMilitaryStatusPreferences", (string)null);
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.Company", b =>
                {
                    b.OwnsOne("GenclikMerkezi.SharedKernel.Domain.FileAttachment", "Logo", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LogoContentType");

                            b1.Property<string>("FileKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("LogoFileKey");

                            b1.Property<string>("OriginalFileName")
                                .IsRequired()
                                .HasMaxLength(260)
                                .HasColumnType("nvarchar(260)")
                                .HasColumnName("LogoOriginalFileName");

                            b1.Property<Guid>("OwnerEntityId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("LogoOwnerEntityId");

                            b1.Property<string>("OwnerEntityType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LogoOwnerEntityType");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("LogoSizeInBytes");

                            b1.Property<DateTime>("UploadedAtUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("LogoUploadedAtUtc");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.JobDrivingLicensePreference", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Employer.Domain.Job", null)
                        .WithMany("DrivingLicensePreferences")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.JobEducationLevelPreference", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Employer.Domain.Job", null)
                        .WithMany("EducationLevelPreferences")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.JobGenderPreference", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Employer.Domain.Job", null)
                        .WithMany("GenderPreferences")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.JobLanguageRequirement", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Employer.Domain.Job", null)
                        .WithMany("LanguageRequirements")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.JobMilitaryStatusPreference", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Employer.Domain.Job", null)
                        .WithMany("MilitaryStatusPreferences")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeedDrivingLicensePreference", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeed", null)
                        .WithMany("DrivingLicensePreferences")
                        .HasForeignKey("PersonnelNeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeedEducationLevelPreference", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeed", null)
                        .WithMany("EducationLevelPreferences")
                        .HasForeignKey("PersonnelNeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeedGenderPreference", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeed", null)
                        .WithMany("GenderPreferences")
                        .HasForeignKey("PersonnelNeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeedMilitaryStatusPreference", b =>
                {
                    b.HasOne("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeed", null)
                        .WithMany("MilitaryStatusPreferences")
                        .HasForeignKey("PersonnelNeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.Job", b =>
                {
                    b.Navigation("DrivingLicensePreferences");

                    b.Navigation("EducationLevelPreferences");

                    b.Navigation("GenderPreferences");

                    b.Navigation("LanguageRequirements");

                    b.Navigation("MilitaryStatusPreferences");
                });

            modelBuilder.Entity("GenclikMerkezi.Modules.Employer.Domain.PersonnelNeed", b =>
                {
                    b.Navigation("DrivingLicensePreferences");

                    b.Navigation("EducationLevelPreferences");

                    b.Navigation("GenderPreferences");

                    b.Navigation("MilitaryStatusPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
