<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="PdfPig" Version="0.1.16" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\SharedKernel\GenclikMerkezi.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\Modules\Candidate\GenclikMerkezi.Modules.Candidate.csproj" />
    <ProjectReference Include="..\..\src\Modules\CareerAdvisor\GenclikMerkezi.Modules.CareerAdvisor.csproj" />
    <ProjectReference Include="..\..\src\Modules\Employer\GenclikMerkezi.Modules.Employer.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\GenclikMerkezi.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\Notification\GenclikMerkezi.Modules.Notification.csproj" />
    <ProjectReference Include="..\..\src\Modules\ReferenceData\GenclikMerkezi.Modules.ReferenceData.csproj" />
  </ItemGroup>

</Project>